-- 1. Create Projects Table
CREATE TABLE IF NOT EXISTS public.projects (
    id TEXT PRIMARY KEY, -- We use TEXT because the app generates timestamp-based IDs
    topic TEXT,
    title TEXT,
    hook TEXT,
    script TEXT,
    platform TEXT[], -- Stores array of strings e.g. ['TikTok', 'Instagram']
    status TEXT,
    scheduled_date TEXT,
    generated_date TEXT,
    virality_score NUMERIC,
    thumbnail_url TEXT,
    video_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- MIGRATION: Ensure video_url exists if the table was created before this column was added
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS video_url TEXT;

-- 2. Create Logs Table
CREATE TABLE IF NOT EXISTS public.logs (
    id TEXT PRIMARY KEY,
    text TEXT,
    type TEXT,
    time_label TEXT, -- Stores the formatted time string like "Just now" or "2 mins ago"
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Settings Table
CREATE TABLE IF NOT EXISTS public.settings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    connected_accounts JSONB DEFAULT '{"youtube": false, "tiktok": false, "instagram": false, "facebook": false}'::jsonb,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Insert Default Settings (Row ID 1)
INSERT INTO public.settings (id, connected_accounts)
VALUES (1, '{"youtube": false, "tiktok": false, "instagram": false, "facebook": false}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- 5. Enable Row Level Security (RLS)
-- This is required by Supabase for security policies to take effect
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- 6. Create Open Access Policies (For Demo/Dev Mode)
-- NOTE: We use DROP POLICY IF EXISTS to avoid "policy already exists" errors when re-running this script.

-- Projects Policies
DROP POLICY IF EXISTS "Enable read access for all users" ON public.projects;
CREATE POLICY "Enable read access for all users" ON public.projects FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert access for all users" ON public.projects;
CREATE POLICY "Enable insert access for all users" ON public.projects FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Enable update access for all users" ON public.projects;
CREATE POLICY "Enable update access for all users" ON public.projects FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Enable delete access for all users" ON public.projects;
CREATE POLICY "Enable delete access for all users" ON public.projects FOR DELETE USING (true);

-- Logs Policies
DROP POLICY IF EXISTS "Enable read access for all users" ON public.logs;
CREATE POLICY "Enable read access for all users" ON public.logs FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert access for all users" ON public.logs;
CREATE POLICY "Enable insert access for all users" ON public.logs FOR INSERT WITH CHECK (true);

-- Settings Policies
DROP POLICY IF EXISTS "Enable read access for all users" ON public.settings;
CREATE POLICY "Enable read access for all users" ON public.settings FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable update access for all users" ON public.settings;
CREATE POLICY "Enable update access for all users" ON public.settings FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Enable insert access for all users" ON public.settings;
CREATE POLICY "Enable insert access for all users" ON public.settings FOR INSERT WITH CHECK (true);
