import { Platform, AccountConfig } from "../types";

// Helper to convert a remote URL to a Blob for uploading
const urlToBlob = async (url: string): Promise<Blob> => {
    // Basic input validation
    if (!url || typeof url !== 'string') {
        throw new Error("Invalid video URL provided");
    }

    try {
        console.log("Fetching video binary from:", url);
        const response = await fetch(url);
        if (!response.ok) {
            throw new Error(`Failed to download video: ${response.status} ${response.statusText}`);
        }
        const blob = await response.blob();
        console.log(`Video downloaded successfully. Size: ${blob.size} bytes, Type: ${blob.type}`);
        return blob;
    } catch (error) {
        console.error("Video Download Error:", error);
        throw new Error("Could not download video data. The video link may have expired or is blocked by CORS.");
    }
};

export const publishingService = {
    async publish(platform: Platform, videoUrl: string, title: string, description: string, config: AccountConfig): Promise<boolean> {
        // Security: Input validation
        if (!platform || !videoUrl || !title) {
             throw new Error("Missing required publishing parameters");
        }
        
        // Security: Credential validation
        if (!config.connected || !config.accessToken) {
            throw new Error(`Account for ${platform} is not connected or missing tokens.`);
        }

        try {
            switch (platform) {
                case 'YouTube Shorts':
                    return await this.publishToYouTube(videoUrl, title, description, config.accessToken);
                case 'Instagram Reels':
                    return await this.publishToInstagram(videoUrl, description, config.accessToken, config.accountId!);
                case 'TikTok':
                    return await this.publishToTikTok(videoUrl, title, config.accessToken);
                default:
                    console.warn(`Publishing to ${platform} not yet implemented.`);
                    return false;
            }
        } catch (error) {
            console.error(`Failed to publish to ${platform}:`, error);
            throw error;
        }
    },

    async publishToYouTube(videoUrl: string, title: string, description: string, token: string): Promise<boolean> {
        console.log("Starting YouTube Resumable Upload...");

        // 1. Get the actual video data
        const videoBlob = await urlToBlob(videoUrl);

        // 2. Metadata for the video
        const metadata = {
            snippet: {
                title: title.substring(0, 100), // Max 100 chars
                description: description || "Generated by ViralFlow AI",
                categoryId: "22", // People & Blogs
                tags: ["AI", "Viral", "Shorts"]
            },
            status: {
                privacyStatus: "private", // Default to private for safety
                selfDeclaredMadeForKids: false
            }
        };

        try {
            // 3. PHASE 1: Start Resumable Session
            // We ask YouTube for a unique upload URL
            const initResponse = await fetch('https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status', {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${token}`,
                    'Content-Type': 'application/json',
                    'X-Upload-Content-Length': videoBlob.size.toString(),
                    'X-Upload-Content-Type': 'video/mp4'
                },
                body: JSON.stringify(metadata)
            });

            if (!initResponse.ok) {
                const errText = await initResponse.text();
                // Check specifically for CORS-like issues or origin issues
                if (initResponse.status === 403 || initResponse.status === 400) {
                     throw new Error(`YouTube Session Init Failed (${initResponse.status}). Ensure 'Authorized JavaScript origins' in GCP Console matches your domain. Details: ${errText}`);
                }
                throw new Error(`YouTube Init Error: ${errText}`);
            }

            // Extract the upload URL from the 'Location' header
            const uploadUrl = initResponse.headers.get('Location');
            if (!uploadUrl) {
                throw new Error("YouTube did not return an upload location header.");
            }

            console.log("Resumable session created. Uploading bytes...");

            // 4. PHASE 2: Upload the actual binary file
            const uploadResponse = await fetch(uploadUrl, {
                method: 'PUT',
                headers: {
                    'Content-Type': 'video/mp4'
                },
                body: videoBlob
            });

            if (!uploadResponse.ok) {
                const uploadErr = await uploadResponse.text();
                throw new Error(`Video Upload Failed: ${uploadErr}`);
            }

            const result = await uploadResponse.json();
            console.log("YouTube Upload Success!", result);
            return true;

        } catch (error: any) {
            console.error("YouTube Upload Critical Failure:", error);
            
            // Provide specific advice for common errors
            if (error.message.includes('Failed to fetch') || error.message.includes('NetworkError')) {
                throw new Error("Network Error: This is usually a CORS block. Please add your current domain (e.g., http://localhost:xxxx) to 'Authorized JavaScript origins' in your Google Cloud Console OAuth Client settings.");
            }
            
            throw error;
        }
    },

    async publishToInstagram(videoUrl: string, caption: string, token: string, igUserId: string): Promise<boolean> {
        if (!igUserId) throw new Error("Instagram User ID is required");

        // Instagram Graph API: 2 Step Process
        try {
            // Step 1: Create Container
            // Note: Video URL must be public and accessible by Facebook servers
            console.log("Creating Instagram Media Container...");
            const containerUrl = `https://graph.facebook.com/v18.0/${igUserId}/media?media_type=REELS&video_url=${encodeURIComponent(videoUrl)}&caption=${encodeURIComponent(caption)}&access_token=${token}`;
            
            const containerRes = await fetch(containerUrl, { method: 'POST' });
            const containerData = await containerRes.json();

            if (containerData.error) throw new Error(`IG Container Error: ${containerData.error.message}`);
            
            const containerId = containerData.id;
            console.log("Container created:", containerId);

            // Wait for processing (Instagram needs time to download the video from the URL)
            console.log("Waiting for Instagram processing...");
            await new Promise(r => setTimeout(r, 8000)); // Increased wait time to 8s

            // Step 2: Publish Container
            console.log("Publishing Container...");
            const publishUrl = `https://graph.facebook.com/v18.0/${igUserId}/media_publish?creation_id=${containerId}&access_token=${token}`;
            const publishRes = await fetch(publishUrl, { method: 'POST' });
            const publishData = await publishRes.json();

            if (publishData.error) throw new Error(`IG Publish Error: ${publishData.error.message}`);

            return true;
        } catch (error: any) {
            console.error("Instagram Publish Error:", error);
             if (error.message === 'Failed to fetch' || error.message.includes('CORS')) {
                console.warn("CORS Error on Instagram. Ensure you are using a proxy or server-side flow in production.");
            }
            throw error;
        }
    },

    async publishToTikTok(videoUrl: string, title: string, token: string): Promise<boolean> {
        // NOTE: TikTok Web API is complex and usually requires server-to-server.
        console.log("Simulating TikTok Upload (Not fully implemented in client-demo)...");
        await new Promise(r => setTimeout(r, 2000));
        return true;
    }
};